<a href="https://colab.research.google.com/github/kausthab88/LearningDeepLearning/blob/main/DL_Basics_contd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

### Creating Random Tensors

Random tensors are tensors of some arbitrary size containing random numbers. The tensor creation process is very similar to numpy rarray creation

In [3]:
# create two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [4]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

#### **Note**

Since we have used the same seed, even though we have used *random* here, the tensors will be the same. That is what seeding does. If you want to learn more about seed, please use this link:

[Tensorflow Seed](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

In [5]:
# Are these tensors equal?

random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [6]:
# Shuffle a tensor (valuable when we want to shuffle our data so that the inherent order does not bias the model)

not_shuffled = tf.constant([[10,7],
                            [3,2],
                            [5,8]])

not_shuffled.ndim


2

In [7]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 5,  8]], dtype=int32)>

In [8]:
#Shuffling the not_shuffled tensor

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 5,  8]], dtype=int32)>

In [9]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  8],
       [ 3,  2],
       [10,  7]], dtype=int32)>

In [10]:
#setting seed to get the same order in shuffle

tf.random.set_seed(1)
tf.random.shuffle(not_shuffled,seed = 1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 5,  8]], dtype=int32)>

In [11]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  2],
       [ 5,  8]], dtype=int32)>

#### **Note**

The next few lines of codes will only make sense to you if you have gone through the Tensorflow Seed link shared earlier

In [12]:
#generating 5 random tensors with/without operational and global seeds

tensor01 = tf.random.Generator.from_seed(seed = 10)
tensor01 = tensor01.normal(shape = (3,3))
tensor01

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.29604465, -0.21134205,  0.01063002],
       [ 1.5165398 ,  0.27305737, -0.29925638],
       [-0.3652325 ,  0.61883307, -1.0130816 ]], dtype=float32)>

In [13]:
tf.random.set_seed(10)
tensor02 = tf.random.normal(shape = (3,2))
tensor02

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.8757808 ,  0.3356369 ],
       [-0.35219625, -0.30314562],
       [-0.03882965,  0.96529824]], dtype=float32)>

In [14]:
tensor02

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.8757808 ,  0.3356369 ],
       [-0.35219625, -0.30314562],
       [-0.03882965,  0.96529824]], dtype=float32)>

In [15]:
tf.random.set_seed(10)
tensor03 = tf.random.normal(shape = (3,2),seed = 10)
tensor03

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.22895075,  0.18573567],
       [ 0.96057963,  0.1884016 ],
       [-1.4445381 , -0.46771628]], dtype=float32)>

In [16]:
tf.random.set_seed(10)
tensor05 = tf.random.normal(shape = (3,2))
tensor05

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.8757808 ,  0.3356369 ],
       [-0.35219625, -0.30314562],
       [-0.03882965,  0.96529824]], dtype=float32)>

In [17]:
tf.random.set_seed(101)
tf.random.shuffle(tensor05,seed = 1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.03882965,  0.96529824],
       [-0.8757808 ,  0.3356369 ],
       [-0.35219625, -0.30314562]], dtype=float32)>

> Rule 4 "If both global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence