<a href="https://colab.research.google.com/github/kausthab88/LearningDeepLearning/blob/main/DL_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Intro to Tensors**

In [1]:
#import TensorFlow

import tensorflow as tf 
print(tf.__version__)

2.12.0


#### 1. **Scalar**

A scalar is a mathematical object with just a single number

In [2]:
#creating tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

##### A scalar will have a dimension of 0. Since it is just a single number it does not have any dimensions

In [3]:
#checking dimension of scalar

scalar.ndim #ndim stands for the number of dimensions

0

#### 2. **Vector**

A vector is an array of numbers (or 1D array )and is ordered as such. We can identify each number by its index in that ordering. This indexing is the same as we index a list





In [4]:
#create a vector

vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

##### A vector is always 1 dimensional

In [5]:
#indexing a vector

vector[1]

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [6]:
#check the dimension of the vector

vector.ndim

1

#### 3. Matrix

A matrix is a 2D array and hence each element is identified by two indices and not one


In [7]:
#create a matrix (has more than 1 dimension)

matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim #checking the dimensions of matrix

2

#### We can specify the datatype of the matrix with the *dtype* parameter

In [9]:
#create another matrix

another_matrix = tf.constant([[1.,2.],
                              [4.,5.],
                              [7.,8.]],dtype=tf.float32) #specify data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [4., 5.],
       [7., 8.]], dtype=float32)>

In [10]:
#number of dimensions for a matrix
another_matrix.ndim

2

#### 4. Tensors

A tensor is a multi-dimensional matrix. That means it has more than 2 axes (unlike a matrix). 

In [11]:
#creating a tensor

tensor = tf.constant([[[1,2,3],
                       [5,6,7]],
                      
                       [[7,8,9],
                      [11,12,13]],
                      
                      [[15,16,17],
                       [21,22,23]]]
                     )
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[ 7,  8,  9],
        [11, 12, 13]],

       [[15, 16, 17],
        [21, 22, 23]]], dtype=int32)>

In [12]:
tensor.ndim #checking the dimensions of a tensors

3

So far we have learnt:
 
* A scalar is a single number
* Vector: a number with direction (e.g speed of a boat going in a particular direction)
* Matrix: 2 dimensional array of numbers
* Tensor: an n-dimensional array of numbers(where n can attain any value: a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector, 2-dimensional tensor is a matrix)