<a href="https://colab.research.google.com/github/kausthab88/LearningDeepLearning/blob/main/Tensor_Dot_Product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

#### **What is a dot product?**

The dot product of two vectors 

a = [a1, a2, ..., an] and b = [b1, b2, ..., bn] is computed as:

a.b = a1xb1 + a2xb2 + ... + anxbn

**Note:** Dot product terminology is used only for vectors resulting in a scalar. When dealing with higher order tensors, we often use terms like "tensor product", "tensor contraction", or "matrix multiplication", because these operations can result in a tensor of various ranks, not just a scalar.

**The Dot Product**

We can also use `tf.tensordot()` as well for performing matrix multiplication in addition to `tf.matmul()`

In [4]:
# create a tensor with shape (3,2)

X = tf.constant([[1,2],
                [3,4],
                [5,6]])

#create another tensor of same shape

Y = tf.constant([[7,8],
                [9,10],
                [11,12]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

When axes = 1, a normal dot product is carried out

In [5]:
#Matrix Multiplication with tensordot and transposing X
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [6]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [7]:
#Matrix multiplication with X and Y reshaped

tf.matmul(X,tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [8]:
#check the values of : Y, reshape Y and transpose Y

print('normal Y: ', Y)
print('\n')
print('reshape Y: ', tf.reshape(Y,shape = (2,3)))
print('\n')
print('Transposed Y: ', tf.transpose(Y))

normal Y:  tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)


reshape Y:  tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


Transposed Y:  tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [9]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [10]:
a = tf.constant([[1,2],[3,4]])
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [11]:
b = tf.constant([[1,2],[1,1]])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 1]], dtype=int32)>

When we use axes = 0, we're not summing over any axes. Instead, we're taking an outer product of the two tensors, an outer product can be thought of as a way to combine every element from the first tensor with every element from the second tensor.

We see below that the resultant is a 4D tensor wherein the first two dimensions are from "a", and the last two dimensions are from "b"

In [12]:
tf.tensordot(a,b,axes = 0)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 2],
         [1, 1]],

        [[2, 4],
         [2, 2]]],


       [[[3, 6],
         [3, 3]],

        [[4, 8],
         [4, 4]]]], dtype=int32)>

In [13]:
b = tf.constant([[1,1],[1,1],[1,1]])
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [14]:
tf.tensordot(a,b,axes = 0)

<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2],
         [2, 2]]],


       [[[3, 3],
         [3, 3],
         [3, 3]],

        [[4, 4],
         [4, 4],
         [4, 4]]]], dtype=int32)>

**We will encounter dot product in Neural Networks while calculating the output y of any network, hence it becomes very important to understand the concept of dot product**