<a href="https://colab.research.google.com/github/kausthab88/LearningDeepLearning/blob/main/Tensors_contd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Other ways to make tensors
import tensorflow as tf
import numpy as np

#### tf.ones creates a tensor that fills the shape with ones. It takes the shape of the parent matrix or tensor

In [3]:
#tensor of all ones
tensor_ones = tf.ones(shape = {10,7}) #for shape we can use a list and a tuple and a set as well
tensor_ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

#### tf.zeros is similar to tf.ones, just fills the matrix or tensor with zeros

In [4]:
#tensor of all zeroes
tensor_zeroes = tf.zeros(shape = [10,10])
tensor_zeroes

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

#### We can create tensors using numpy arrays. A step by step implementation is shown below. After declaring the numpy array we just need to pass it as a tensor using tf.constant. We can use any shape we want by passing the 'shape' argument.

In [5]:
numpy_A = np.arange(1,25,dtype = 'int32')
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [6]:
A = tf.constant(value = numpy_A, shape = {2,3,4})
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [7]:
A.ndim

3

### Getting more info from tensors

Tensor attributes

* Shape
* Rank
* Axis or dimension
* Size

#### Rank of a tensor is the number of axes. This is also given by *ndim*

* A scalar has no axes

* A vector has one axes 

* A matrix has 2 axes

In [8]:
#create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [9]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

#### Shape of a tensor is a tuple that shows how many dimensions the tensor has along each axis whereas size of a tensor shows the total number of elements a tensor has

In [10]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [11]:
#Getting various attributes of the tensor

print('The data type of our tensor is ',rank_4_tensor.dtype)
print('The shape of our tensor is ',rank_4_tensor.shape)
print('The number of dimensions of our tensor is (rank) ',rank_4_tensor.ndim)
print('Elements along 0-axis ',rank_4_tensor.shape[0])
print('Elements along last axis ',rank_4_tensor.shape[-1])
print('Total number of elements in our tensor is ',tf.size(rank_4_tensor))
print('Total number of elements in our tensor is ',tf.size(rank_4_tensor).numpy())

The data type of our tensor is  <dtype: 'float32'>
The shape of our tensor is  (2, 3, 4, 5)
The number of dimensions of our tensor is (rank)  4
Elements along 0-axis  2
Elements along last axis  5
Total number of elements in our tensor is  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor is  120


### Slicing a tensor

We can slice tensors based on their dimensions

In [12]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [13]:
# Get the first element from each dimension from each index except for the final one

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [14]:

rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [15]:
rank_4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [16]:
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

### Adding an extra dimension to a tensor

In [17]:
# Create a rank 2 tensor (2 dimensions)

rank_2_tensor = tf.constant(value = np.random.randint(np.arange(5,9)),shape = [2,2])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[2, 5],
       [6, 1]])>

In [18]:
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [19]:
# Get the last item of each row

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([5, 1])>

#### tf.newaxis just increases the existing arrays dimension by one more dimension as shown below

In [20]:
# Adding an extra dimension

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int64, numpy=
array([[[2],
        [5]],

       [[6],
        [1]]])>

In [21]:
#Another representation of the above code
rank_3_tensor = rank_2_tensor[:,:, tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int64, numpy=
array([[[2],
        [5]],

       [[6],
        [1]]])>

#### tf.expand_dims allows us to expand dimensions basis the axis. If we put axis = 0, it will add a dimension at the beginning i.e position 0 and if we use axis = 1, it will add postion 1

In [22]:
# Alterntive to tf.newaxis

tf.expand_dims(rank_2_tensor,axis = -1) #extra dimension at the end

<tf.Tensor: shape=(2, 2, 1), dtype=int64, numpy=
array([[[2],
        [5]],

       [[6],
        [1]]])>

In [23]:
tf.expand_dims(rank_2_tensor,axis = 0) #extra dimension at the beginning

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[2, 5],
        [6, 1]]])>

In [24]:

tf.expand_dims(rank_2_tensor,axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int64, numpy=
array([[[2],
        [5]],

       [[6],
        [1]]])>

In [25]:
tf.expand_dims(rank_2_tensor,axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int64, numpy=
array([[[2, 5],
        [6, 1]]])>

In [26]:
tf.expand_dims(rank_2_tensor,axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int64, numpy=
array([[[2, 5]],

       [[6, 1]]])>