<a href="https://colab.research.google.com/github/kausthab88/LearningDeepLearning/blob/main/TensorManipulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import tensorflow as tf
import numpy as np

### Changing the data type of a tensor

In [2]:
# create a new tensor with default datatype (float32)

B = tf.constant([1.2,7.4])
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 7.4], dtype=float32)>,
 tf.float32)

##### Tensors like numpy can detect the datatype of the elements automatically

In [3]:
C = tf.constant([7,10])
C,C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [4]:
C_dup = tf.constant([7.,10.])
C_dup,C_dup.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

##### As mentioned earlier, the default datatype for float elements is `float32` and for int it is `int32`

In [6]:
# Change from float32 to flat16 -- also caled reduced precision (refer documentation)

D = tf.constant([7,10],dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

#### The **cast** function helps in changing the data type of a tensor. It can also change the datatype from a higher to lower order and vice versa

In [5]:
E = tf.cast(B,dtype=tf.float16)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 7.4], dtype=float16)>,
 tf.float16)

In [7]:
# Change from int32 to float32

F = tf.constant([10,20])

F, F.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>,
 tf.int32)

In [8]:
G = tf.cast(F, dtype = tf.float32)

G, G.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 20.], dtype=float32)>,
 tf.float32)

In [9]:
#Getting the absolute values

D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [10]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation

* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of tensor

In [11]:
# Create a random tensor

H = tf.random.Generator.from_seed(seed = 100)

J = H.normal(shape = ((5,3)))

J


<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[-0.90112925, -0.0175216 , -0.4188493 ],
       [ 0.29532313,  0.08036723, -1.7199678 ],
       [-0.6891769 ,  0.22862972, -0.69891334],
       [-0.11101238, -0.44537356,  0.1335287 ],
       [ 0.12417295,  0.96785086, -0.35425642]], dtype=float32)>

In [12]:
tf.reduce_min(J)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.7199678>

In [13]:
tf.reduce_max(J)

<tf.Tensor: shape=(), dtype=float32, numpy=0.96785086>

In [14]:
tf.math.reduce_mean(J)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.23508854>

In [17]:
H = tf.constant(np.random.randint(1,100, size = 50))

H

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([99,  2, 97, 11, 74, 13, 73, 78, 43, 67, 31, 57, 89, 49, 26, 14,  8,
       79, 19, 69, 12, 38, 88, 32, 85, 32, 15, 41, 27, 76, 18, 30, 60, 32,
       20, 46, 81, 56, 12, 12, 63, 63, 62, 15, 87,  5, 94, 18, 79, 56])>

In [18]:
#find the minimum

tf.reduce_min(H)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [19]:
#find the maximum

tf.reduce_max(H)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [20]:
# Find the mean

tf.reduce_mean(H)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [21]:
#Find the sum

tf.reduce_sum(H)

<tf.Tensor: shape=(), dtype=int64, numpy=2353>

In [22]:
tf.cast(H,dtype = tf.float16)

<tf.Tensor: shape=(50,), dtype=float16, numpy=
array([99.,  2., 97., 11., 74., 13., 73., 78., 43., 67., 31., 57., 89.,
       49., 26., 14.,  8., 79., 19., 69., 12., 38., 88., 32., 85., 32.,
       15., 41., 27., 76., 18., 30., 60., 32., 20., 46., 81., 56., 12.,
       12., 63., 63., 62., 15., 87.,  5., 94., 18., 79., 56.],
      dtype=float16)>


##### If we use the math library to find the variance or the standard deviation, we have to convert the elements to a `float` datatype

In [27]:
# Find the standard deviation

tf.math.reduce_variance(tf.cast(H,dtype = tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=846.5>

In [24]:
# Find the standard deviation


tf.math.reduce_std(tf.cast(H,dtype = tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=29.1>