<a href="https://colab.research.google.com/github/kausthab88/LearningDeepLearning/blob/main/Tensor_Manipulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

### Manipulating Tensors (tensor operations)

** Basic operations**

`+`, `-`, `*`, `/`

#### **Note**

We cannot add tensors of different shapes

#### When we add a number to a tensor, it will add that number to all the elements in that tensor. Similar is the case when we do sunbtraction, multiplication or division

In [23]:
# Addition operator adds a value to the entire tensor

tensor = tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [4]:
tensor + 10 # This does not change the original tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [5]:
# Subtraction

tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [6]:
# Multiplication

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [7]:
# Division

tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.3, 0.4]])>

#### Using TF inbuilt functions

Alternatively we can use the tensorflow inbuild add, subtract , divide and multiply functions and achieve the exact results

In [9]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [10]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

#### Matrix Multiplication

Matrix multiplication is one of the most important concepts to be understood. In order to multiply 2 matrices, the gollowing rule have to satisfy:

1. The inner dimension of the matrices must match
2. The resulting matrix will have the shape of outer dimensions

In [24]:
#Matrix Multiplication in Tensorflow

print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [12]:
tensor * tensor # is not same as matmul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [13]:
# Matrix multiplication with Python operator "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [25]:
# Matrix multiplication with different shape

# create a tensor with shape (3,2)

X = tf.constant([[1,2],
                [3,4],
                [5,6]])


In [15]:
Y = tf.constant([[7,8,9],
                [10,11,12]])

Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [16]:
X@Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [17]:
Z = tf.constant([[11,12,13,14],
                 [15,16,17,18]])

Z

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[11, 12, 13, 14],
       [15, 16, 17, 18]], dtype=int32)>

In [18]:
X @ Z

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]], dtype=int32)>

#### Reshaping a tensor vs Transposing a Tensor

* Reshape is an operation that allows you to change the shape of a tensor while preserving the total number of elements in it. It rearranges the elements of the tensor to fit a new shape without changing the order or values of the elements



In [19]:
# REshaping X
# Let's define Y first

Y = tf.constant([[7,8],
                [9,10],
                [11,12]])
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [26]:
tf.reshape(X,shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [20]:
tf.matmul(tf.reshape(X,shape = (2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

* Transpose on the other hand is an operation that swaps the dimensions of a tensor. It reorders the axes of a tensor, effectively rotating the tensor along its axes

In [21]:
# Can do the same with transpose

X, tf.transpose(X), tf.reshape(X, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [22]:
# Trying Matrix multiplication with transpose rather than reshape

tf.matmul(tf.transpose(X),Y) #Transpose changes the axis rather than shuffling the number as reshape does

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

#### Hence we see that, reshape and transpose will both give us different results