<a href="https://colab.research.google.com/github/kausthab88/LearningDeepLearning/blob/main/Tensor_Manipulations_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

### Find the positional maximum and minimum

In [3]:
H = tf.constant(np.random.randint(1,100, size = 50))

H

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([96, 84, 35, 95, 31, 76, 50,  9, 78, 69, 90, 80, 14, 88, 40, 86,  4,
       40, 73, 40, 80, 10,  6, 88,  4, 42, 68, 54, 48, 13, 36, 20, 17, 42,
       41, 51, 37, 53, 59, 71, 56, 72, 85, 72, 22, 95, 71,  3, 27, 63])>

In [4]:
max(H)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

`argmax` gives the index of the maximum element in an array

In [5]:
tf.math.argmax(H)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

`argmin` gives the index of the minimum element in an array

In [6]:
tf.math.argmin(H)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [7]:
# Create a new tensor to find the positional max and min

tf.random.set_seed(42)

E = tf.random.uniform(shape = [50])

E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [8]:
#Finding the positional maximum

tf.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [9]:
E[tf.argmax(E)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [10]:
#Finding the positional minimum

tf.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [11]:
#Finding the positional minimum 

E[tf.argmin(E)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [12]:
#Finding the max value of E

tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

*Please note- assert is not meant to produce output, it is used as a debugging tool*

In [17]:
#checking for equality

assert E[tf.argmax(E)] == tf.reduce_max(E)

### Squeezing a tensor (removing all single dimensions)

In [18]:
K = tf.constant(tf.random.uniform(shape = [50]),shape = (1,1,1,1,50))
K

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [19]:
K.shape

TensorShape([1, 1, 1, 1, 50])

**The tf.squeeze function is a transformation used to remove dimensions of size one from the shape of a tensor. Specifically, given a tensor input, this operation returns a tensor of the same type with all dimensions of size 1 removed** 


In [20]:
K_squeezed = tf.squeeze(K)

K_squeezed, K_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]))